### PR TITLE
PAXCDI-164 @OsgiServiceProvider: Support ParameterizedType

### PR DESCRIPTION
**Pull request by puce77**
- Support for ParameterizedType added

### CODE REVIEW

**Comment by hwellmann** [comment]
Thanks for the patch! Could you please add a test that verifies the problem and the fix?

**Comment by puce77** [comment]
How do you test classes in this project? I couldn't find any unit test for pax-cdi-extension, neither in src/main/test nor in a fragment bundle...

**Comment by hwellmann** [comment]
The tests are under `itest`, e.g. `itest/src/it/itest-cdi10`.

**Comment by puce77** [comment]
I've added a test case (in itest-standalone) and a sample.

**Comment by puce77** [comment]
It would be great if you could merge this pull request as keeping it up-to-date with the master branch manually is rather time consuming.

**Comment by hwellmann** [comment]
See comment in PAXCDI-164 on why this is incomplete.

**Comment by puce77** [comment]
? I provided the test (including client side) already back on 6th May!? https://github.com/puce77/org.ops4j.pax.cdi/blob/ada0aaa7ed4dd1f6158e1acb7a0c5d35ea3e65d9/itest/src/it/itest-standalone/src/test/java/org/ops4j/pax/cdi/test/ParameterizedTypeSupportTest.java

**Comment by hwellmann** [comment]
@cmoulliard This should not have been merged, see comments in JIRA. 

Besides, integration tests are currently broken. See http://ci.ops4j.org/jenkins/job/org.ops4j.pax.cdi-itest/

**Pull request merged**
